### ISSUE TITLE
Strange error Class not found : js.html.HTMLDocument

### ISSUE THREAD

**Issue by vnedilko** [webgroup-limited/id.net-haxe-sdk#1]
haxe 3.1.3
source/idnet/js/_Social.hx:11: characters 7-27 : Class not found : js.html.HTMLDocument

**Comment by vnedilko** [comment]
I is related to haxe 3.1.3

**Comment by Codir** [comment]
Hi,
If You using 3.1.x, then You can change js.html.HTMLDocument to js.html.Document in source/idnet/js/_Social.hx.
For 3.2.x need using js.html.HTMLDocument

**Comment by vnedilko** [comment]
Question. Did current state version production ready?

**Comment by Codir** [comment]
> Question. Did current state version production ready?

Yes. You can use this sdk for flash and HTML5 target. But it is constantly evolving. And I making changes and fix when need

**Comment by vnedilko** [comment]
Now after make changes you noted, have another issue:
Social.get_i().setAuthorized(true); //Not found
source/idnet/js/_Social.hx:183: characters 4-32 : idnet.Social has no field setAuthorized (Suggestion: isAuthorized)

**Comment by Codir** [comment]
> Now after make changes you noted, have another issue:
> Social.get_i().setAuthorized(true); //Not found
> source/idnet/js/_Social.hx:183: characters 4-32 : idnet.Social has no field setAuthorized (Suggestion: isAuthorized)

Thanks. Updated
